---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - {{ .Values.PersistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.storage }}