{{- if .Values.verticalScaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-vpa
  labels:
    app: {{ .Release.Name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: {{ .Values.verticalScaling.vpamode }}
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: "250m"
        memory: "512Mi"
      maxAllowed:
        cpu: "500m"
        memory: "1024Mi"
{{- end }}